### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [tunjid/digilux-android#1]
Would you mind offering an alternative download source for those outside of Play Store – e.g. attaching the APKs to their resp. `releases/`, or maybe bringing the app to [F-Droid](https://f-droid.org/)?

**Comment by tunjid** [comment]
@IzzySoft I'll put it on F-Droid as soon as I figure out how!

**Comment by IzzySoft** [comment]
Oh, that's great! Being one of the maintainers there, I can get you started with that: First step would be [filing an RFP](https://gitlab.com/fdroid/rfp/issues) – OK, [done that](https://gitlab.com/fdroid/rfp/issues/1033). Now we wait for the F-Droid bot to verify your repo (should run within the next ~10h). Hopefully it gives an "all green", so next a packager sees if it builds and, if so, adds it to the repo. Might take a few days until the last step (signing, which is manual on a disconnected server) is through, and your app finally turns up in the index.

Please check with the linked issue if the bot turned up anything; if you have a GitLab account, be welcome to chime in there.

Apart from that, nice to have would be if you could setup Fastlane (or Triple-T) with your repo here to provide screenshots and maybe also summary, descriptions and per-release changelogs. That would also cover your Play Store releases then – so "one place to rule them all". For starters, there's [this page](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) in the F-Droid docs.

Let me know if you need further help with this, and I see what I can do. Thanks a lot!

**Comment by IzzySoft** [comment]
OK, the bot was there – and unfortunately had some things to complain about. Could you please check?

    ERROR: Found unknown maven repo 'https://oss.jfrog.info/artifactory/oss-snapshot-local' at build.gradle

(listed twice). F-Droid only permits "white-listed" maven repos. A maven repo can be white-listed under certain conditions (most importantly, always shipping the source). So if we cannot white-list this one, can whatever you take from there be found in a different maven repo [that is white-listed](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L99) (maybe you just need to replace `jfrog.info` by `jfrog.org`)? Alternatively, is the source available so we could include that as `srclib`?

Insecure gradle: That part should be easy to fix, and rather concerns your own builds (so it's no stopper for F-Droid).

**Comment by tunjid** [comment]
@IzzySoft I'll go through my dependencies to see which ones pull from that, it may not be necessary. I think It was from an internal dependency I published as a SNAPSHOT before putting it on Maven.

**Comment by IzzySoft** [comment]
Even better then! What's not there cannot raise issues (or have bugs/security-issues at that) :smile: As the bot wasn't following up any tag but just went straight to HEAD: Just let me know when you think it's worth it, and I have it run again. A new tag covering that can be created when the bot finally says "go" (I'd adjust metadata then to point to the new tag).

**Comment by tunjid** [comment]
@IzzySoft Removed!

**Comment by IzzySoft** [comment]
@tunjid thanks! Kicked the bot (should run again within the next ~20h – I don't remember the exact schedule, it's somewhere in the early morning hours UTC). Will report back with the results.

**Comment by IzzySoft** [comment]
\o/ The bot accepted it. Marked it for our packagers then who will test the build and, if that works without issues, merge it. I'll keep you updated on the progress.

**Comment by IzzySoft** [comment]
Thanks again – and congrats!
