### ISSUE TITLE
Pick An Action menu unresponsive

### ISSUE THREAD

**Issue by hoshmn** [tunjid/digilux-android#2]
When I attempt to assign an action through the Pick an action menu in the Gestures tab, I'm unable to select an option (my clicks don't do anything), meaning I'm stuck with the defaults. 

I'm on a Pixel 3a, latest Android 9, no special configuration.

Also, any way to enable brightness swipe adjustments from the lock screen? My main use case is pulling out my phone while biking outside and not easily being able to read the time/notifications (and not a fan of auto-adjusting brightness :) ).

Thanks!

**Comment by tunjid** [comment]
Hey @hoshmn, sorry I missed this earlier. Thanks for the bug report, I've reproduced it and I should have an update to fix it tonight.

For the other use case, is your lock screen pin or fingerprint protected? If so, the fingerprint sensor will not respond to gestures as it thinks you're trying to unlock the phone.

**Comment by tunjid** [comment]
@hoshmn Fixed!

**Comment by hoshmn** [comment]
Thanks so much! I appreciate your work on the app, very useful. And gotcha, that makes sense on the locked screen limitation (it is fingerprint protected)
