### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [tunjid/digilux-android#7]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by tunjid** [comment]
@mondlicht-und-sterne thanks for the heads up, will give it a go when I find some time. If it's not too much to ask, and you don't mind doing it, please feel free to contribute them.

**Comment by mondlicht-und-sterne** [comment]
Since the issue dates back a long time - can you just close
the issue? Thank you, my initial Issie was also just information.
