### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [tunjid/digilux-android#8]
Ref: https://f-droid.org/wiki/index.php?title=com.tunjid.fingergestures/lastbuild_53&oldid=285211

**Comment by tunjid** [comment]
@licaon-kter this was due to a bad lint config from one of the Google libraries, should be fixed on the latest branches.

**Comment by licaon-kter** [comment]
So in the next version or when exactly?

**Comment by tunjid** [comment]
@licaon-kter Version/tag 10.0.2 builds successfully.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9207

**Comment by TPS** [comment]
v10.0.2 is released on F-Droid 6-15-21.  Close FTW?
